name: Week 11-12 Task 2 (custom interfaces) - CI in Docker

on:
  push:
  pull_request:

jobs:
  task2_custom_interfaces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build course Docker image (from this repo or main course repo)
        run: |
          set -euxo pipefail
          if [ -f docker/Dockerfile ]; then
            docker build -t tro029-ci -f docker/Dockerfile docker
          elif [ -f Dockerfile ]; then
            docker build -t tro029-ci -f Dockerfile .
          else
            git clone --depth 1 https://github.com/Tallinna-Tehnika-korgkool/TRO029---ROS2-sissejuhatus.git /tmp/tro029-course
            if [ -f /tmp/tro029-course/docker/Dockerfile ]; then
              docker build -t tro029-ci -f /tmp/tro029-course/docker/Dockerfile /tmp/tro029-course/docker
            elif [ -f /tmp/tro029-course/Dockerfile ]; then
              docker build -t tro029-ci -f /tmp/tro029-course/Dockerfile /tmp/tro029-course
            else
              echo "ERROR: Could not find Dockerfile in this repo or in the main course repo."
              exit 1
            fi
          fi

      - name: Build and test tutorial_interfaces + updated nodes
        run: |
          set -euxo pipefail
          docker run --rm             -v "${{ github.workspace }}:/repo"             --entrypoint /bin/bash             --user root             tro029-ci -lc '
              set -euo pipefail
              export DEBIAN_FRONTEND=noninteractive

              # Source ROS 2
              if [ -f /opt/ros/humble/setup.bash ]; then
                source /opt/ros/humble/setup.bash
              else
                source /opt/ros/${ROS_DISTRO:-humble}/setup.bash
              fi

              # Ensure tooling exists (best-effort)
              command -v colcon >/dev/null 2>&1 || (apt-get update && apt-get install -y python3-colcon-common-extensions)
              command -v rosdep >/dev/null 2>&1 || (apt-get update && apt-get install -y python3-rosdep rsync)
              command -v rsync >/dev/null 2>&1 || (apt-get update && apt-get install -y rsync)

              rosdep init 2>/dev/null || true
              rosdep update 2>/dev/null || true

              WS=/tmp/ros2_ws
              rm -rf "$WS"
              mkdir -p "$WS/src"

              rsync -a --exclude ".git" /repo/ "$WS/src/student_repo/"

              # Find required packages
              TI_XML=$(grep -Rsl "<name>tutorial_interfaces</name>" "$WS/src/student_repo" | head -n1 || true)
              PUB_XML=$(grep -Rsl "<name>py_pubsub</name>" "$WS/src/student_repo" | head -n1 || true)
              SRV_XML=$(grep -Rsl "<name>py_srvcli</name>" "$WS/src/student_repo" | head -n1 || true)

              if [ -z "$TI_XML" ]; then
                echo "ERROR: tutorial_interfaces not found."
                exit 1
              fi
              if [ -z "$PUB_XML" ]; then
                echo "ERROR: py_pubsub not found (needed for Num.msg pub/sub test)."
                exit 1
              fi
              if [ -z "$SRV_XML" ]; then
                echo "ERROR: py_srvcli not found (needed for AddThreeInts service/client test)."
                exit 1
              fi

              TI_DIR=$(dirname "$TI_XML")
              PUB_DIR=$(dirname "$PUB_XML")
              SRV_DIR=$(dirname "$SRV_XML")

              echo "Found tutorial_interfaces at: $TI_DIR"
              echo "Found py_pubsub at: $PUB_DIR"
              echo "Found py_srvcli at: $SRV_DIR"

              cp -a "$TI_DIR" "$WS/src/tutorial_interfaces"
              cp -a "$PUB_DIR" "$WS/src/py_pubsub"
              cp -a "$SRV_DIR" "$WS/src/py_srvcli"

              # Quick static checks that code was updated to use custom interfaces
              grep -R "from tutorial_interfaces.msg import Num" -n "$WS/src/py_pubsub/py_pubsub" >/dev/null                 || (echo "ERROR: py_pubsub does not import Num from tutorial_interfaces (expected code update)" && exit 1)

              grep -R "from tutorial_interfaces.srv import AddThreeInts" -n "$WS/src/py_srvcli/py_srvcli" >/dev/null                 || (echo "ERROR: py_srvcli does not import AddThreeInts from tutorial_interfaces (expected code update)" && exit 1)

              grep -q "<exec_depend>tutorial_interfaces</exec_depend>" "$WS/src/py_pubsub/package.xml"                 || (echo "ERROR: py_pubsub/package.xml missing <exec_depend>tutorial_interfaces</exec_depend>" && exit 1)

              grep -q "<exec_depend>tutorial_interfaces</exec_depend>" "$WS/src/py_srvcli/package.xml"                 || (echo "ERROR: py_srvcli/package.xml missing <exec_depend>tutorial_interfaces</exec_depend>" && exit 1)

              cd "$WS"
              rosdep install -i --from-paths src --rosdistro humble -y --ignore-src 2>/dev/null || true

              # Build everything needed
              colcon build --packages-select tutorial_interfaces py_pubsub py_srvcli
              source install/setup.bash

              # Verify interfaces are discoverable
              ros2 interface show tutorial_interfaces/msg/Num | grep -q "int64 num"
              ros2 interface show tutorial_interfaces/msg/Sphere | grep -q "float64 radius"
              ros2 interface show tutorial_interfaces/srv/AddThreeInts | grep -q "int64 c"

              # Smoke test pub/sub with Num.msg
              rm -f /tmp/listener.log /tmp/talker.log
              timeout 8s ros2 run py_pubsub listener > /tmp/listener.log 2>&1 &
              LIST_PID=$!
              sleep 1
              timeout 4s ros2 run py_pubsub talker > /tmp/talker.log 2>&1 || true
              sleep 1
              kill $LIST_PID 2>/dev/null || true
              wait $LIST_PID 2>/dev/null || true

              echo "--- pubsub listener.log (tail) ---"
              tail -n 50 /tmp/listener.log || true

              # Expect integer prints
              grep -Eiq "I heard:.*[0-9]+" /tmp/listener.log                 || (echo "ERROR: listener did not show integer messages (Num.msg)" && exit 1)

              # Smoke test service/client with AddThreeInts (2+3+1=6)
              rm -f /tmp/service.log /tmp/client.log
              timeout 10s ros2 run py_srvcli service > /tmp/service.log 2>&1 &
              SRV_PID=$!
              sleep 1
              timeout 8s ros2 run py_srvcli client 2 3 1 > /tmp/client.log 2>&1 || true
              sleep 1
              kill $SRV_PID 2>/dev/null || true
              wait $SRV_PID 2>/dev/null || true

              echo "--- srvcli client.log (tail) ---"
              tail -n 50 /tmp/client.log || true
              echo "--- srvcli service.log (tail) ---"
              tail -n 50 /tmp/service.log || true

              grep -Eiq "Result of add_three_ints:.*2 \+ 3 \+ 1 = 6" /tmp/client.log                 || (echo "ERROR: client output did not include expected result (2+3+1=6)" && exit 1)

              grep -Eiq "Incoming request" /tmp/service.log                 || (echo "ERROR: service did not log Incoming request" && exit 1)

              grep -Eiq "a: 2 b: 3 c: 1" /tmp/service.log                 || (echo "ERROR: service did not log expected request values (a: 2 b: 3 c: 1)" && exit 1)

              echo "OK: tutorial_interfaces + updated pubsub + updated srvcli passed."
            '
